//DO NOT EDIT, AUTO-GENORATED
using ASCOM.Common.Alpaca;
using ASCOM.Simulators;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Net.Mime;

namespace ASCOM.Alpaca.Simulators
{
    /// <summary>
    /// Autogenerated DO NOT EDIT
    /// OmniSim only, not part of Alpaca
    /// </summary>
    [ServiceFilter(typeof(AuthorizationFilter))]
    [ApiController]
    [Route("simulator/v1/")]
    public class CoverCalibratorSimulatorSettingsController : ProcessBaseController
    {
        /// <summary>
        /// OmniSim Only - The ASCOM Interface Version, allowed values are 1-2
        /// </summary>
        /// <remarks>
        /// <para>The ASCOM Interface Version, allowed values are 1-2</para>
        /// </remarks>
        /// <param name="DeviceNumber">Zero based device number as set on the server (A uint32 with a range of 0 to 4294967295)</param>
        /// <param name="ClientID">Client's unique ID.</param>
        /// <param name="ClientTransactionID">Client's transaction ID.</param>
        /// <response code="200">Transaction complete or exception</response>
        /// <response code="400" examples="Error message describing why the command cannot be processed">Method or parameter value error, check error message</response>
        /// <response code="500" examples="Error message describing why the command cannot be processed">Server internal error, check error message</response>
        [HttpGet]
        [Produces(MediaTypeNames.Application.Json)]
        [ApiExplorerSettings(GroupName = "OmniSim")]
        [Route("covercalibratorsimulator/{DeviceNumber}/interfaceversion")]
        public ActionResult<ASCOM.Common.Alpaca.IntResponse> InterfaceVersion(
            [Required][DefaultValue(0)][SwaggerSchema(Strings.DeviceIDDescription, Format = "uint32")][Range(0, 4294967295)] uint DeviceNumber,
            [SwaggerSchema(Strings.ClientIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientID = 0,
            [SwaggerSchema(Strings.ClientTransactionIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientTransactionID = 0)
        {
            return ProcessRequest(() => ((DeviceManager.GetCoverCalibrator(DeviceNumber) as ASCOM.Simulators.CoverCalibratorSimulator)).InterfaceVersionSetting.Value, DeviceManager.ServerTransactionID, ClientID, ClientTransactionID);
        }
        /// <summary>
        /// OmniSim Only - The ASCOM Interface Version, allowed values are 1-2
        /// </summary>
        /// <remarks>
        /// <para>The ASCOM Interface Version, allowed values are 1-2</para>
        /// </remarks>
        /// <param name="DeviceNumber">Zero based device number as set on the server (A uint32 with a range of 0 to 4294967295)</param>
        /// <param name="InterfaceVersion">The ASCOM Interface Version, allowed values are 1-2</param>
        /// <param name="ClientID">Client's unique ID.</param>
        /// <param name="ClientTransactionID">Client's transaction ID.</param>
        /// <response code="200">Transaction complete or exception</response>
        /// <response code="400" examples="Error message describing why the command cannot be processed">Method or parameter value error, check error message</response>
        /// <response code="500" examples="Error message describing why the command cannot be processed">Server internal error, check error message</response>
        [HttpPut]
        [Produces(MediaTypeNames.Application.Json)]
        [ApiExplorerSettings(GroupName = "OmniSim")]
        [Route("covercalibratorsimulator/{DeviceNumber}/interfaceversion")]
        public ActionResult<Response> InterfaceVersion(
            [Required][DefaultValue(0)][SwaggerSchema(Strings.DeviceIDDescription, Format = "uint32")][Range(0, 4294967295)] uint DeviceNumber,
            [Required][FromForm][SwaggerSchema("The ASCOM Interface Version, allowed values are 1-2")] System.Int16 InterfaceVersion,
            [FromForm][SwaggerSchema(Strings.ClientIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientID = 0,
            [FromForm][SwaggerSchema(Strings.ClientTransactionIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientTransactionID = 0)
        {
            return ProcessRequest(() => { ((DeviceManager.GetCoverCalibrator(DeviceNumber) as ASCOM.Simulators.CoverCalibratorSimulator)).InterfaceVersionSetting.Value = InterfaceVersion; }, DeviceManager.ServerTransactionID, ClientID, ClientTransactionID, $"InterfaceVersion={InterfaceVersion}");
        }
        /// <summary>
        /// OmniSim Only - The delay to be used for Connect() in milliseconds, allowed values are 1-30000
        /// </summary>
        /// <remarks>
        /// <para>The delay to be used for Connect() in milliseconds, allowed values are 1-30000</para>
        /// </remarks>
        /// <param name="DeviceNumber">Zero based device number as set on the server (A uint32 with a range of 0 to 4294967295)</param>
        /// <param name="ClientID">Client's unique ID.</param>
        /// <param name="ClientTransactionID">Client's transaction ID.</param>
        /// <response code="200">Transaction complete or exception</response>
        /// <response code="400" examples="Error message describing why the command cannot be processed">Method or parameter value error, check error message</response>
        /// <response code="500" examples="Error message describing why the command cannot be processed">Server internal error, check error message</response>
        [HttpGet]
        [Produces(MediaTypeNames.Application.Json)]
        [ApiExplorerSettings(GroupName = "OmniSim")]
        [Route("covercalibratorsimulator/{DeviceNumber}/connectdelay")]
        public ActionResult<ASCOM.Common.Alpaca.IntResponse> ConnectDelay(
            [Required][DefaultValue(0)][SwaggerSchema(Strings.DeviceIDDescription, Format = "uint32")][Range(0, 4294967295)] uint DeviceNumber,
            [SwaggerSchema(Strings.ClientIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientID = 0,
            [SwaggerSchema(Strings.ClientTransactionIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientTransactionID = 0)
        {
            return ProcessRequest(() => ((DeviceManager.GetCoverCalibrator(DeviceNumber) as ASCOM.Simulators.CoverCalibratorSimulator)).ConnectDelay.Value, DeviceManager.ServerTransactionID, ClientID, ClientTransactionID);
        }
        /// <summary>
        /// OmniSim Only - The delay to be used for Connect() in milliseconds, allowed values are 1-30000
        /// </summary>
        /// <remarks>
        /// <para>The delay to be used for Connect() in milliseconds, allowed values are 1-30000</para>
        /// </remarks>
        /// <param name="DeviceNumber">Zero based device number as set on the server (A uint32 with a range of 0 to 4294967295)</param>
        /// <param name="ConnectDelay">The delay to be used for Connect() in milliseconds, allowed values are 1-30000</param>
        /// <param name="ClientID">Client's unique ID.</param>
        /// <param name="ClientTransactionID">Client's transaction ID.</param>
        /// <response code="200">Transaction complete or exception</response>
        /// <response code="400" examples="Error message describing why the command cannot be processed">Method or parameter value error, check error message</response>
        /// <response code="500" examples="Error message describing why the command cannot be processed">Server internal error, check error message</response>
        [HttpPut]
        [Produces(MediaTypeNames.Application.Json)]
        [ApiExplorerSettings(GroupName = "OmniSim")]
        [Route("covercalibratorsimulator/{DeviceNumber}/connectdelay")]
        public ActionResult<Response> ConnectDelay(
            [Required][DefaultValue(0)][SwaggerSchema(Strings.DeviceIDDescription, Format = "uint32")][Range(0, 4294967295)] uint DeviceNumber,
            [Required][FromForm][SwaggerSchema("The delay to be used for Connect() in milliseconds, allowed values are 1-30000")] System.Int16 ConnectDelay,
            [FromForm][SwaggerSchema(Strings.ClientIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientID = 0,
            [FromForm][SwaggerSchema(Strings.ClientTransactionIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientTransactionID = 0)
        {
            return ProcessRequest(() => { ((DeviceManager.GetCoverCalibrator(DeviceNumber) as ASCOM.Simulators.CoverCalibratorSimulator)).ConnectDelay.Value = ConnectDelay; }, DeviceManager.ServerTransactionID, ClientID, ClientTransactionID, $"ConnectDelay={ConnectDelay}");
        }
        /// <summary>
        /// OmniSim Only - Max Brightness Range 1-2147483647 default (100)
        /// </summary>
        /// <remarks>
        /// <para>Max Brightness Range 1-2147483647 default (100)</para>
        /// </remarks>
        /// <param name="DeviceNumber">Zero based device number as set on the server (A uint32 with a range of 0 to 4294967295)</param>
        /// <param name="ClientID">Client's unique ID.</param>
        /// <param name="ClientTransactionID">Client's transaction ID.</param>
        /// <response code="200">Transaction complete or exception</response>
        /// <response code="400" examples="Error message describing why the command cannot be processed">Method or parameter value error, check error message</response>
        /// <response code="500" examples="Error message describing why the command cannot be processed">Server internal error, check error message</response>
        [HttpGet]
        [Produces(MediaTypeNames.Application.Json)]
        [ApiExplorerSettings(GroupName = "OmniSim")]
        [Route("covercalibratorsimulator/{DeviceNumber}/maximumbrightness")]
        public ActionResult<ASCOM.Common.Alpaca.IntResponse> MaximumBrightness(
            [Required][DefaultValue(0)][SwaggerSchema(Strings.DeviceIDDescription, Format = "uint32")][Range(0, 4294967295)] uint DeviceNumber,
            [SwaggerSchema(Strings.ClientIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientID = 0,
            [SwaggerSchema(Strings.ClientTransactionIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientTransactionID = 0)
        {
            return ProcessRequest(() => ((DeviceManager.GetCoverCalibrator(DeviceNumber) as ASCOM.Simulators.CoverCalibratorSimulator)).MaximumBrightness.Value, DeviceManager.ServerTransactionID, ClientID, ClientTransactionID);
        }
        /// <summary>
        /// OmniSim Only - Max Brightness Range 1-2147483647 default (100)
        /// </summary>
        /// <remarks>
        /// <para>Max Brightness Range 1-2147483647 default (100)</para>
        /// </remarks>
        /// <param name="DeviceNumber">Zero based device number as set on the server (A uint32 with a range of 0 to 4294967295)</param>
        /// <param name="MaximumBrightness">Max Brightness Range 1-2147483647 default (100)</param>
        /// <param name="ClientID">Client's unique ID.</param>
        /// <param name="ClientTransactionID">Client's transaction ID.</param>
        /// <response code="200">Transaction complete or exception</response>
        /// <response code="400" examples="Error message describing why the command cannot be processed">Method or parameter value error, check error message</response>
        /// <response code="500" examples="Error message describing why the command cannot be processed">Server internal error, check error message</response>
        [HttpPut]
        [Produces(MediaTypeNames.Application.Json)]
        [ApiExplorerSettings(GroupName = "OmniSim")]
        [Route("covercalibratorsimulator/{DeviceNumber}/maximumbrightness")]
        public ActionResult<Response> MaximumBrightness(
            [Required][DefaultValue(0)][SwaggerSchema(Strings.DeviceIDDescription, Format = "uint32")][Range(0, 4294967295)] uint DeviceNumber,
            [Required][FromForm][SwaggerSchema("Max Brightness Range 1-2147483647 default (100)")] System.Int32 MaximumBrightness,
            [FromForm][SwaggerSchema(Strings.ClientIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientID = 0,
            [FromForm][SwaggerSchema(Strings.ClientTransactionIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientTransactionID = 0)
        {
            return ProcessRequest(() => { ((DeviceManager.GetCoverCalibrator(DeviceNumber) as ASCOM.Simulators.CoverCalibratorSimulator)).MaximumBrightness.Value = MaximumBrightness; }, DeviceManager.ServerTransactionID, ClientID, ClientTransactionID, $"MaximumBrightness={MaximumBrightness}");
        }
        /// <summary>
        /// OmniSim Only - Max Brightness Range 1-100.0 default (2.0)
        /// </summary>
        /// <remarks>
        /// <para>Max Brightness Range 1-100.0 default (2.0)</para>
        /// </remarks>
        /// <param name="DeviceNumber">Zero based device number as set on the server (A uint32 with a range of 0 to 4294967295)</param>
        /// <param name="ClientID">Client's unique ID.</param>
        /// <param name="ClientTransactionID">Client's transaction ID.</param>
        /// <response code="200">Transaction complete or exception</response>
        /// <response code="400" examples="Error message describing why the command cannot be processed">Method or parameter value error, check error message</response>
        /// <response code="500" examples="Error message describing why the command cannot be processed">Server internal error, check error message</response>
        [HttpGet]
        [Produces(MediaTypeNames.Application.Json)]
        [ApiExplorerSettings(GroupName = "OmniSim")]
        [Route("covercalibratorsimulator/{DeviceNumber}/calibratorstabilisationtime")]
        public ActionResult<ASCOM.Common.Alpaca.DoubleResponse> CalibratorStabilisationTime(
            [Required][DefaultValue(0)][SwaggerSchema(Strings.DeviceIDDescription, Format = "uint32")][Range(0, 4294967295)] uint DeviceNumber,
            [SwaggerSchema(Strings.ClientIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientID = 0,
            [SwaggerSchema(Strings.ClientTransactionIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientTransactionID = 0)
        {
            return ProcessRequest(() => ((DeviceManager.GetCoverCalibrator(DeviceNumber) as ASCOM.Simulators.CoverCalibratorSimulator)).CalibratorStablisationTime.Value, DeviceManager.ServerTransactionID, ClientID, ClientTransactionID);
        }
        /// <summary>
        /// OmniSim Only - Max Brightness Range 1-100.0 default (2.0)
        /// </summary>
        /// <remarks>
        /// <para>Max Brightness Range 1-100.0 default (2.0)</para>
        /// </remarks>
        /// <param name="DeviceNumber">Zero based device number as set on the server (A uint32 with a range of 0 to 4294967295)</param>
        /// <param name="CalibratorStabilisationTime">Max Brightness Range 1-100.0 default (2.0)</param>
        /// <param name="ClientID">Client's unique ID.</param>
        /// <param name="ClientTransactionID">Client's transaction ID.</param>
        /// <response code="200">Transaction complete or exception</response>
        /// <response code="400" examples="Error message describing why the command cannot be processed">Method or parameter value error, check error message</response>
        /// <response code="500" examples="Error message describing why the command cannot be processed">Server internal error, check error message</response>
        [HttpPut]
        [Produces(MediaTypeNames.Application.Json)]
        [ApiExplorerSettings(GroupName = "OmniSim")]
        [Route("covercalibratorsimulator/{DeviceNumber}/calibratorstabilisationtime")]
        public ActionResult<Response> CalibratorStabilisationTime(
            [Required][DefaultValue(0)][SwaggerSchema(Strings.DeviceIDDescription, Format = "uint32")][Range(0, 4294967295)] uint DeviceNumber,
            [Required][FromForm][SwaggerSchema("Max Brightness Range 1-100.0 default (2.0)")] System.Double CalibratorStabilisationTime,
            [FromForm][SwaggerSchema(Strings.ClientIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientID = 0,
            [FromForm][SwaggerSchema(Strings.ClientTransactionIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientTransactionID = 0)
        {
            return ProcessRequest(() => { ((DeviceManager.GetCoverCalibrator(DeviceNumber) as ASCOM.Simulators.CoverCalibratorSimulator)).CalibratorStablisationTime.Value = CalibratorStabilisationTime; }, DeviceManager.ServerTransactionID, ClientID, ClientTransactionID, $"CalibratorStabilisationTime={CalibratorStabilisationTime}");
        }
        /// <summary>
        /// OmniSim Only - Cover Opening Time 1-100.0 default (5.0)
        /// </summary>
        /// <remarks>
        /// <para>Cover Opening Time 1-100.0 default (5.0)</para>
        /// </remarks>
        /// <param name="DeviceNumber">Zero based device number as set on the server (A uint32 with a range of 0 to 4294967295)</param>
        /// <param name="ClientID">Client's unique ID.</param>
        /// <param name="ClientTransactionID">Client's transaction ID.</param>
        /// <response code="200">Transaction complete or exception</response>
        /// <response code="400" examples="Error message describing why the command cannot be processed">Method or parameter value error, check error message</response>
        /// <response code="500" examples="Error message describing why the command cannot be processed">Server internal error, check error message</response>
        [HttpGet]
        [Produces(MediaTypeNames.Application.Json)]
        [ApiExplorerSettings(GroupName = "OmniSim")]
        [Route("covercalibratorsimulator/{DeviceNumber}/coveropeningtime")]
        public ActionResult<ASCOM.Common.Alpaca.DoubleResponse> CoverOpeningTime(
            [Required][DefaultValue(0)][SwaggerSchema(Strings.DeviceIDDescription, Format = "uint32")][Range(0, 4294967295)] uint DeviceNumber,
            [SwaggerSchema(Strings.ClientIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientID = 0,
            [SwaggerSchema(Strings.ClientTransactionIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientTransactionID = 0)
        {
            return ProcessRequest(() => ((DeviceManager.GetCoverCalibrator(DeviceNumber) as ASCOM.Simulators.CoverCalibratorSimulator)).CoverOpeningTime.Value, DeviceManager.ServerTransactionID, ClientID, ClientTransactionID);
        }
        /// <summary>
        /// OmniSim Only - Cover Opening Time 1-100.0 default (5.0)
        /// </summary>
        /// <remarks>
        /// <para>Cover Opening Time 1-100.0 default (5.0)</para>
        /// </remarks>
        /// <param name="DeviceNumber">Zero based device number as set on the server (A uint32 with a range of 0 to 4294967295)</param>
        /// <param name="CoverOpeningTime">Cover Opening Time 1-100.0 default (5.0)</param>
        /// <param name="ClientID">Client's unique ID.</param>
        /// <param name="ClientTransactionID">Client's transaction ID.</param>
        /// <response code="200">Transaction complete or exception</response>
        /// <response code="400" examples="Error message describing why the command cannot be processed">Method or parameter value error, check error message</response>
        /// <response code="500" examples="Error message describing why the command cannot be processed">Server internal error, check error message</response>
        [HttpPut]
        [Produces(MediaTypeNames.Application.Json)]
        [ApiExplorerSettings(GroupName = "OmniSim")]
        [Route("covercalibratorsimulator/{DeviceNumber}/coveropeningtime")]
        public ActionResult<Response> CoverOpeningTime(
            [Required][DefaultValue(0)][SwaggerSchema(Strings.DeviceIDDescription, Format = "uint32")][Range(0, 4294967295)] uint DeviceNumber,
            [Required][FromForm][SwaggerSchema("Cover Opening Time 1-100.0 default (5.0)")] System.Double CoverOpeningTime,
            [FromForm][SwaggerSchema(Strings.ClientIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientID = 0,
            [FromForm][SwaggerSchema(Strings.ClientTransactionIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientTransactionID = 0)
        {
            return ProcessRequest(() => { ((DeviceManager.GetCoverCalibrator(DeviceNumber) as ASCOM.Simulators.CoverCalibratorSimulator)).CoverOpeningTime.Value = CoverOpeningTime; }, DeviceManager.ServerTransactionID, ClientID, ClientTransactionID, $"CoverOpeningTime={CoverOpeningTime}");
        }
        /// <summary>
        /// OmniSim Only - Calibrator Initialisation State, allowed values (NotPresent = 0, Off = 1, NotReady = 2, Ready = 3, Unknown = 4, Error = 5) default Off
        /// </summary>
        /// <remarks>
        /// <para>Calibrator Initialisation State, allowed values (NotPresent = 0, Off = 1, NotReady = 2, Ready = 3, Unknown = 4, Error = 5) default Off</para>
        /// </remarks>
        /// <param name="DeviceNumber">Zero based device number as set on the server (A uint32 with a range of 0 to 4294967295)</param>
        /// <param name="ClientID">Client's unique ID.</param>
        /// <param name="ClientTransactionID">Client's transaction ID.</param>
        /// <response code="200">Transaction complete or exception</response>
        /// <response code="400" examples="Error message describing why the command cannot be processed">Method or parameter value error, check error message</response>
        /// <response code="500" examples="Error message describing why the command cannot be processed">Server internal error, check error message</response>
        [HttpGet]
        [Produces(MediaTypeNames.Application.Json)]
        [ApiExplorerSettings(GroupName = "OmniSim")]
        [Route("covercalibratorsimulator/{DeviceNumber}/calibratorinitialisationstate")]
        public ActionResult<ASCOM.Common.Alpaca.StringResponse> CalibratorInitialisationState(
            [Required][DefaultValue(0)][SwaggerSchema(Strings.DeviceIDDescription, Format = "uint32")][Range(0, 4294967295)] uint DeviceNumber,
            [SwaggerSchema(Strings.ClientIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientID = 0,
            [SwaggerSchema(Strings.ClientTransactionIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientTransactionID = 0)
        {
            return ProcessRequest(() => ((DeviceManager.GetCoverCalibrator(DeviceNumber) as ASCOM.Simulators.CoverCalibratorSimulator)).CalibratorStateInitialisation.Value, DeviceManager.ServerTransactionID, ClientID, ClientTransactionID);
        }
        /// <summary>
        /// OmniSim Only - Calibrator Initialisation State, allowed values (NotPresent = 0, Off = 1, NotReady = 2, Ready = 3, Unknown = 4, Error = 5) default Off
        /// </summary>
        /// <remarks>
        /// <para>Calibrator Initialisation State, allowed values (NotPresent = 0, Off = 1, NotReady = 2, Ready = 3, Unknown = 4, Error = 5) default Off</para>
        /// </remarks>
        /// <param name="DeviceNumber">Zero based device number as set on the server (A uint32 with a range of 0 to 4294967295)</param>
        /// <param name="CalibratorInitialisationState">Calibrator Initialisation State, allowed values (NotPresent = 0, Off = 1, NotReady = 2, Ready = 3, Unknown = 4, Error = 5) default Off</param>
        /// <param name="ClientID">Client's unique ID.</param>
        /// <param name="ClientTransactionID">Client's transaction ID.</param>
        /// <response code="200">Transaction complete or exception</response>
        /// <response code="400" examples="Error message describing why the command cannot be processed">Method or parameter value error, check error message</response>
        /// <response code="500" examples="Error message describing why the command cannot be processed">Server internal error, check error message</response>
        [HttpPut]
        [Produces(MediaTypeNames.Application.Json)]
        [ApiExplorerSettings(GroupName = "OmniSim")]
        [Route("covercalibratorsimulator/{DeviceNumber}/calibratorinitialisationstate")]
        public ActionResult<Response> CalibratorInitialisationState(
            [Required][DefaultValue(0)][SwaggerSchema(Strings.DeviceIDDescription, Format = "uint32")][Range(0, 4294967295)] uint DeviceNumber,
            [Required][FromForm][SwaggerSchema("Calibrator Initialisation State, allowed values (NotPresent = 0, Off = 1, NotReady = 2, Ready = 3, Unknown = 4, Error = 5) default Off")] System.String CalibratorInitialisationState,
            [FromForm][SwaggerSchema(Strings.ClientIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientID = 0,
            [FromForm][SwaggerSchema(Strings.ClientTransactionIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientTransactionID = 0)
        {
            return ProcessRequest(() => { ((DeviceManager.GetCoverCalibrator(DeviceNumber) as ASCOM.Simulators.CoverCalibratorSimulator)).CalibratorStateInitialisation.Value = CalibratorInitialisationState; }, DeviceManager.ServerTransactionID, ClientID, ClientTransactionID, $"CalibratorInitialisationState={CalibratorInitialisationState}");
        }
        /// <summary>
        /// OmniSim Only - Cover Initialisation State, allowed values (NotPresent = 0, Closed = 1, Moving = 2, Open = 3, Unknown = 4, Error = 5) default Off
        /// </summary>
        /// <remarks>
        /// <para>Cover Initialisation State, allowed values (NotPresent = 0, Closed = 1, Moving = 2, Open = 3, Unknown = 4, Error = 5) default Off</para>
        /// </remarks>
        /// <param name="DeviceNumber">Zero based device number as set on the server (A uint32 with a range of 0 to 4294967295)</param>
        /// <param name="ClientID">Client's unique ID.</param>
        /// <param name="ClientTransactionID">Client's transaction ID.</param>
        /// <response code="200">Transaction complete or exception</response>
        /// <response code="400" examples="Error message describing why the command cannot be processed">Method or parameter value error, check error message</response>
        /// <response code="500" examples="Error message describing why the command cannot be processed">Server internal error, check error message</response>
        [HttpGet]
        [Produces(MediaTypeNames.Application.Json)]
        [ApiExplorerSettings(GroupName = "OmniSim")]
        [Route("covercalibratorsimulator/{DeviceNumber}/coverinitialisationstate")]
        public ActionResult<ASCOM.Common.Alpaca.StringResponse> CoverInitialisationState(
            [Required][DefaultValue(0)][SwaggerSchema(Strings.DeviceIDDescription, Format = "uint32")][Range(0, 4294967295)] uint DeviceNumber,
            [SwaggerSchema(Strings.ClientIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientID = 0,
            [SwaggerSchema(Strings.ClientTransactionIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientTransactionID = 0)
        {
            return ProcessRequest(() => ((DeviceManager.GetCoverCalibrator(DeviceNumber) as ASCOM.Simulators.CoverCalibratorSimulator)).CoverStateInitialisation.Value, DeviceManager.ServerTransactionID, ClientID, ClientTransactionID);
        }
        /// <summary>
        /// OmniSim Only - Cover Initialisation State, allowed values (NotPresent = 0, Closed = 1, Moving = 2, Open = 3, Unknown = 4, Error = 5) default Off
        /// </summary>
        /// <remarks>
        /// <para>Cover Initialisation State, allowed values (NotPresent = 0, Closed = 1, Moving = 2, Open = 3, Unknown = 4, Error = 5) default Off</para>
        /// </remarks>
        /// <param name="DeviceNumber">Zero based device number as set on the server (A uint32 with a range of 0 to 4294967295)</param>
        /// <param name="CoverInitialisationState">Cover Initialisation State, allowed values (NotPresent = 0, Closed = 1, Moving = 2, Open = 3, Unknown = 4, Error = 5) default Off</param>
        /// <param name="ClientID">Client's unique ID.</param>
        /// <param name="ClientTransactionID">Client's transaction ID.</param>
        /// <response code="200">Transaction complete or exception</response>
        /// <response code="400" examples="Error message describing why the command cannot be processed">Method or parameter value error, check error message</response>
        /// <response code="500" examples="Error message describing why the command cannot be processed">Server internal error, check error message</response>
        [HttpPut]
        [Produces(MediaTypeNames.Application.Json)]
        [ApiExplorerSettings(GroupName = "OmniSim")]
        [Route("covercalibratorsimulator/{DeviceNumber}/coverinitialisationstate")]
        public ActionResult<Response> CoverInitialisationState(
            [Required][DefaultValue(0)][SwaggerSchema(Strings.DeviceIDDescription, Format = "uint32")][Range(0, 4294967295)] uint DeviceNumber,
            [Required][FromForm][SwaggerSchema("Cover Initialisation State, allowed values (NotPresent = 0, Closed = 1, Moving = 2, Open = 3, Unknown = 4, Error = 5) default Off")] System.String CoverInitialisationState,
            [FromForm][SwaggerSchema(Strings.ClientIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientID = 0,
            [FromForm][SwaggerSchema(Strings.ClientTransactionIDDescription, Format = "uint32")][Range(0, 4294967295)] uint ClientTransactionID = 0)
        {
            return ProcessRequest(() => { ((DeviceManager.GetCoverCalibrator(DeviceNumber) as ASCOM.Simulators.CoverCalibratorSimulator)).CoverStateInitialisation.Value = CoverInitialisationState; }, DeviceManager.ServerTransactionID, ClientID, ClientTransactionID, $"CoverInitialisationState={CoverInitialisationState}");
        }
}
}
