version: "3"
services:
    web:
        build: .
        ports:
            - "80:32323"
            - "32323:32323"
            - "32227:32227/udp"
        command: ["dotnet", "ascom.alpaca.simulators.dll", "--urls=http://*:32323"]